import Link from 'next/link';
import './globals.scss';
import { Inter } from 'next/font/google';
import Navigation from './navigation/navigation';
import { SSRProvider } from 'react-bootstrap';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Pottery Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SSRProvider>
        <body className={inter.className}>
          <Navigation></Navigation>
          {children}
        </body>
      </SSRProvider>
    </html>
  );
}
