import './globals.scss';
import { Inter } from 'next/font/google';
import Navigation from './navigation/navigation';

const inter = Inter({ subsets: ['latin'] });

//export const metadata = {
//title: 'Pottery World!',
//description: 'Generated by create next app',
//};

export default function RootLayout({ children }) {
  return (
    <>
      <Navigation></Navigation>
      <main>{children}</main>
    </>
  );
}
